### ISSUE TITLE
Moment test breaks several hashes including xxh3

### ISSUE THREAD

**Issue by wangyi-fudan** [rurban/smhasher#65]
```
void MomentTest ( pfHash hash){
	printf("Running MomentTest...\n");
	unsigned	k=0,	s=0;
	unsigned long long l,	h,	x;
	long double sa=0,	saa=0,	sb=0,	sbb=0,	n=0xffffffffull;
	hash(&k,4,s,&l);	for(unsigned	i=1;	i>0;	i++){	hash(&i,4,s,&h);	x=__builtin_popcountll(l^h);	x=x*x*x*x*x;	sa+=x;	saa+=x*x;	l=h;	}
	hash(&k,4,s,&l);	for(unsigned	i=1;	i>0;	i++){	hash(&k,4,i,&h);	x=__builtin_popcountll(l^h);	x=x*x*x*x*x;	sb+=x;	sbb+=x*x;	l=h;	}
	sa/=n;	saa=(saa/n-sa*sa)/n;	sb/=n;	sbb=(sbb/n-sb*sb)/n;	double	chi2=(sa-sb)*(sa-sb)/(saa+sbb);
	printf("KeySeedMomentChi2:\t%g\t%s\n",	chi2,	chi2>3.84145882069413?"FAIL!!!!":"PASS");
}
```
64bit hash chisq:
t1ha2_atonce	0.0170684	PASS
wyhash	0.0347747	PASS
xxHash64	0.145062	PASS
MUM	0.589962	PASS
farmhash64_c	1.05341	PASS
SipHash	2.38213	PASS
(c)metrohash64_2	3.43323	PASS
Spooky64	14.5622	FAIL
(c)metrohash64_1	674.801	FAIL
fasthash64	15556.8	FAIL
xxh3	117826	FAIL

32bit hash chisq:
GoodOAAT	0.00156549	PASS
MUMlow:	0.0022278	PASS
City32	0.0325398	PASS
wyhash32low	0.0465943	PASS
fasthash32	1.7319	PASS
City64low	4.3816	FAIL
Spooky32	34.9565	FAIL
xxHash32	344.586	FAIL
Murmur3A	97936.1	FAIL

wyhash have been updated accord to this new finding :-)

**Comment by rurban** [comment]
Thanks, that's the ultimate test, just extremely slow iterating 2x over the complete keyset. How small can we make the iterations to still get the same confidence?  I think at least a tenth should be good enough.

**Comment by rurban** [comment]
Merged with a236cd24b49a9da08b882b952839f4e8c5a012de

**Comment by Cyan4973** [comment]
What is the MomentChi test ?
What is it supposed to determine ?

**Comment by wangyi-fudan** [comment]
Dear Cyan4973:
The idea behind monentChi is that when hashing 64bit keys, seed and key should be equivelent. any statistics applied to hash(key,seed) should have similar behavier when applied to hash(seed,key). The detailed method is shown in the code. The fail of the test means that the seed is not fully diffused. Usually we use some fixed seeds and considier this is not a serious problem, but in some applications we want different seed to return complete different results.

**Comment by Cyan4973** [comment]
> The fail of the test means that the seed is not fully diffused. 

I thought we already had a "seed" test ?
https://github.com/rurban/smhasher/blob/master/main.cpp#L980 

> The detailed method is shown in the code.

I wouldn't mind an explanation.

My understanding of this code is that it counts the nb of bits changed between 2 consecutive hashes, and uses that as a proxy for distribution quality (without even bothering about exact positions). Then, it magnifies this value by applying a power 5, and then sum them. 
So now, thanks to the power 5, only the largest `popcount` values matter, the smaller ones doesn't. 
What the test effectively checks is if the nb of `popcount==31` and `popcount==30` is exactly the same, since any minor difference in these categories will have a huge impact. Then differences in smaller categories, such as `popcount<10`, do not matter.

In which ways does this test check if the impact of the `seed` value is "diffuse" ?

> any statistics applied to hash(key,seed) should have similar behavier when applied to hash(seed,key).  (...) The fail of the test means that the seed is not fully diffused. 

I don't understand the link between the 2 statements.

One can easily imagine a hash algorithm where the impact of `seed+1` and `key+1` are entirely different, yet both fully diffuse. Why should they be interchangeable, up to their impact on the hash statistics ? This basically requires input to use a commutative form like `seed+key` or `seed^key` or `seed*key`, and specifically for the case where `len(input)==len(seed)`. That might be great for a prng, but I fail to appreciate how this design restriction benefits a hash.

#### Is that about measuring the quality of seed diffusion ?

If the goal is to ensure that the impact of the seed is fully diffused, then the distribution impact of the `seed` should be fully analyzed, and independently. There's no point in comparing its statistics with something else. They could actually be both exactly as bad, that wouldn't make the `seed` fully diffuse.

And that's exactly what the `seed` test does btw, as it uses exactly the same distribution test as all the other tests in the test suite.

One way to improve this test could be to run it at multiple input lengths (say, for example, 3, 8, 16, 32, 64, 128, 256), so that the result is not attached to a single specific length. That would be desirable as nowadays the seed can be treated differently depending on the input size.

**Comment by wangyi-fudan** [comment]
Dear Cyan4973:
most of your understanding is right with a few comments: the hash is 64 bits, thus popcountll ranges [0,64]. not only 63,64 matters, 0 an 1 also matters. too little contribution is a kind of negative contribution. so the power 5 gives more weights on extream values at both end. 
Yes, there is a key test already. But this test uses 4G hashes thus pocess high statistical power. 
maybe my English is not good enough, but fail on this test did hints some problem on the seed part.
Yours,
Yi

**Comment by Cyan4973** [comment]
The following hash passes the `momentChi` test perfectly : 

```
./SMHasher --test=MomentChi2 donothing64
```

Other great candidates include the hash algorithm `key+seed`, and `key^seed`, 
all excellent hashes as we know.

`momentChi` test just _requires_ `seed` and `key` to be _interchangeable_, whatever the underlying quality of the algorithm. It doesn't prove anything with regards to `seed` diffusion quality.

**Comment by wangyi-fudan** [comment]
Dear Cyan4973:
In statistics, passing a test does not imply that it is good. But fail on a test means it is not good. That is why we need a set of tests on hashes from different angles. doningnothing passed momentschi, but will fail on other tests. if it passes all tests, we have to admit that till now we can not break it. 
The momentchi has two passes, one for the key and one for the seed. Finally we compare them. However, the result of two passes can be compared to a absolute values assuming hash produces uniform distributed random numbers. When comparing to absoulte expectations, we can known if key is weak or seed is weak. Because my math is weak, I uses key-vs-seed trick to let one fight with himself in the mirror.

**Comment by Cyan4973** [comment]
This test is requiring something very strange :  it compares 2 sets of transitions (since it counts the number of changed bits when input change from 1 -> 2, then 2-> 3), and requires them to be _equal_, or at least feature exactly the same count of important outliers (since they dominate the final evaluation). Who said that a good hash must guarantee that the serie of transitions when the `seed` changes must be equal to the serie of transitions when the value of `fixed-length-input` changes ? Sounds like a completely arbitrary condition to me.

Comparing vs a kind of "absolute" distribution would indeed be better,
but then, I find this test does not bring anything valuable compared to the regular distribution test,
which is way more complete in term of exact bit distributions and transitions,
while this one summarizes too much, is more noisy, and driven by extreme outliers.
A bit like hyperloglog, 
but hyperloglog features mitigation techniques for outliers, and here there is none.

It's not enough to add a test with some arbitrary condition and say that "a good hash must pass it".
It would be too easy to introduce arbitrary restriction which favor some algorithm and blame others while bringing no value to the table.
In this case, algorithms that ingest seed-size input and seed in a commutative operation simply "game" this test, because they necessarily produce the same serie, by definition. I don't see why it makes them "better", and I don't see why algorithms that produce different series of values depending on modifying the input or the seed would _necessarily_ be worse.

**Comment by espoal** [comment]
is there any research paper that you could link to justify the parameters picked? (degrees of freedom 2, power 5%)

Honestly after taking the time to run the tests myself and analyzing the algorithm used, I'm still dubious about the choices taken. Looking forward to learn more if there is any research that justify the choices.
