### ISSUE TITLE
wyhash32low Quality Problem may be misreported in README.md

### ISSUE THREAD

**Issue by nwbrad** [rurban/smhasher#90]
I apologize in advance if I misunderstood this, but in looking for a 32 bit hash, I thought I might use the wyhash32low hash, but it has a quality problem note of "Moment Chi2 4.2".
But, when I look at the results directly, the file reports the following:

[[[ MomentChi2 Tests ]]]
Running 1st unseeded MomentChi2 for the low 32bits/step 3 ... 1391271.568815 - 1031.004829
Running 2nd   seeded MomentChi2 for the low 32bits/step 3 ... 1391245.333321 - 1030.881595
KeySeedMomentChi2:	0.333821	PASS

Based on the information in the file, the Moment Chi2 is 0.333821 not 4.2.  Is that correct?
I have to admit I not sure I understand the Moment Chi2, but I wanted to research it further since it was noted as a quality problem with wyhash32low.  But in examining the file, it appears to really be a misprint.  

Does that mean the wyhash32low does not have a quality problem and is safe to use as a 32 bit hash?

Thanks

**Comment by wangyi-fudan** [comment]
I am the developer of wyhash and MomentChi2 test. I would like to commnet that even MomentChi2=4.2 does not mean bad but means marginal good. That is a p-value of ~0.03, which can naturally occur sometimes due to pure randomness. SHA256 show similar marginal behavir as you benchmarks ~100 hash functions (multiple testing). A MomentChi2>10 means definitely bad.
Also, recently wyhash have been updated, so this value change with version.
the take-home message is that wyhash/wyhash32low are both HIGH quality hashes.

**Comment by nwbrad** [comment]
Thanks.  That is good to know!

**Comment by rurban** [comment]
Thanks for pointing out the wrong README table. Fixed with ccf2e0c2fcfb5a8869344518cefa6c5b0f58b7b4
